/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_benlai_prototype_bsdiff_PatchUtil */

#ifndef _Included_com_benlai_prototype_bsdiff_PatchUtil
#define _Included_com_benlai_prototype_bsdiff_PatchUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_benlai_prototype_bsdiff_PatchUtil
 * Method:    bspatch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_benlai_prototype_bsdiff_PatchUtil_bspatch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
